services:
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    network_mode: 'host' # TODO Rhydian should probably not use host network mode...
    volumes:
      - /home/rhydian/jellyfin/config:/config
      - /home/rhydian/jellyfin/cache:/cache
      - /mnt/media/Movies:/movies
      - /mnt/media/Shows:/shows
    restart: 'unless-stopped'
